In [2]:
#numpy

import numpy as np
arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(arr1)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [3]:
array2=np.array([1,2,3,34])
array2

array([ 1,  2,  3, 34])

In [4]:
type(array2)

numpy.ndarray

In [5]:
np.shape(arr1)

(2, 5)

In [7]:
np.shape(array2)

(4,)

In [10]:
#reshape the array

array2.reshape(1,4)

array([[ 1,  2,  3, 34]])

In [11]:
array3=np.array([[1,2,3,4,5],[0,9,8,7,6]])
print(array3)

[[1 2 3 4 5]
 [0 9 8 7 6]]


In [13]:
np.shape(array3)

(2, 5)

In [15]:
#build the array through the predefine functions and methods

b=np.arange(1,50,2)
print(b)

b.sum()


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


np.int64(625)

In [16]:
b.reshape(5,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [ ]:
#create the array with size of the 3,4 with the values of 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
##identity matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
##attribute
print('Array',b)
print('shape',b.shape)
print('diemention of array ',b.ndim)
print("size of array",b.size)
print('data type ',b.dtype)
print('items size (in byte)',b.itemsize)

Array [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
shape (25,)
diemention of array  1
size of array 25
data type  int64
items size (in byte) 8


In [21]:
#numpy vectorize operation

a1=np.array([1,2,3,4,5])
a2=np.array([1,2,3,4,5])

#addition
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


In [ ]:
#math function
print(np.sqrt(a1))

print(np.exp(a1))

print(np.sin(a1))

print(np.log(a1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
#array slicing and indexing
exm=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(exm)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [30]:
exm[0][0]

np.int64(1)

In [29]:
exm[1:]

array([[6, 7, 8, 9, 0]])

In [31]:
exm[0:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [32]:
exm[0:][2:4]

array([], shape=(0, 5), dtype=int64)

In [34]:
#modify the array element
exm[0,0]=100
exm

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,   0]])

In [ ]:
#statistical concept

mean=np.mean(a1)
std_dev=np.std(a1)

normalization=a1-mean/std_dev
print("normalization data: ",normalization)
#convert the data in the way that our mean is zero and std dev is 1

normalization data:  [-1.12132034 -0.12132034  0.87867966  1.87867966  2.87867966]


In [37]:
median=np.median(a1)
print("median",median)


variance=np.var(a1)
print("variance: ",variance)

median 3.0
variance:  2.0


In [38]:
#logical operation
a1>5


array([False, False, False, False, False])

In [40]:
a1[(a1 >= 2) & (a1 < 10)]

array([2, 3, 4, 5])