In [ ]:
import pandas as pd
import numpy as np
#when we don't have to assign rank we use label encoding

#Label Encoding 
#Label Encoding assigns a unique integer to each category without implying any order.
#It only converts categorical text data to numeric, but no meaning is attached to the numbers.

In [2]:
df=pd.DataFrame(
    {'color':['red','green','blue','green','red','blue','red','green']}
)
df

,color
0,red
1,green
2,blue
3,green
4,red
5,blue
6,red
7,green


In [3]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
lbl_encode=LabelEncoder()

In [4]:
lbl_encode.fit_transform(df['color'])


array([2, 1, 0, 1, 2, 0, 2, 1])

In [5]:
lbl_encode.transform(['red'])

array([2])

In [6]:
#when we have to assign rank we use ordinal encoding
#Ordinal Encoding is used when the categories have a meaningful order or ranking.
#The encoded numbers reflect the order of the categories.
from sklearn.preprocessing import OrdinalEncoder

df=pd.DataFrame(
    {
        'size':["small","medium","large","medium","small","large","small","medium"]
    }
)
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large
6,small
7,medium


In [8]:
#create instance of OrdinalEncoder and then fit_transform

encoder=OrdinalEncoder(categories=[['small','medium','large']])

encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.]])

In [9]:
encoder.transform([['small']])

C:\Users\jadha\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [ ]:
#Target Guild Ordinal Encoding
#In Target Guided Ordinal Encoding, we replace each category with the mean of the target variable for that category.
#This method is particularly useful when there is a strong relationship between the categorical feature and the target

In [10]:
df=pd.DataFrame({
    'city':['new york','londan','korea','japan','new york','korea','londan','japan'],
    'price':[500,200,300,400,450,350,250,420]
})

In [11]:
df

,city,price
0,new york,500
1,londan,200
2,korea,300
3,japan,400
4,new york,450
5,korea,350
6,londan,250
7,japan,420


In [14]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [15]:
mean_price

{'japan': 410.0, 'korea': 325.0, 'londan': 225.0, 'new york': 475.0}

In [16]:
df['city_encoded']=df['city'].map(mean_price)

In [17]:
df

,city,price,city_encoded
0,new york,500,475.0
1,londan,200,225.0
2,korea,300,325.0
3,japan,400,410.0
4,new york,450,475.0
5,korea,350,325.0
6,londan,250,225.0
7,japan,420,410.0


In [19]:
df[['price','city_encoded']]

,price,city_encoded
0,500,475.0
1,200,225.0
2,300,325.0
3,400,410.0
4,450,475.0
5,350,325.0
6,250,225.0
7,420,410.0


In [20]:
import seaborn as sns


In [21]:
df=sns.load_dataset('tips')

In [23]:
df[['total_bill','time']]

,total_bill,time
0,16.99,Dinner
1,10.34,Dinner
2,21.01,Dinner
3,23.68,Dinner
4,24.59,Dinner
...,...,...
239,29.03,Dinner
240,27.18,Dinner
241,22.67,Dinner
242,17.82,Dinner


In [25]:
encoder=df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\jadha\AppData\Local\Temp\ipykernel_2052\1310383775.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  encoder=df.groupby('time')['total_bill'].mean().to_dict()


In [26]:
encoder

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [28]:
df['time_encoder'] = df['time'].map(encoder)

In [29]:
df[['total_bill','time_encoder']]

,total_bill,time_encoder
0,16.99,20.797159
1,10.34,20.797159
2,21.01,20.797159
3,23.68,20.797159
4,24.59,20.797159
...,...,...
239,29.03,20.797159
240,27.18,20.797159
241,22.67,20.797159
242,17.82,20.797159
